const {test,after}=require('node:test'),assert=require('node:assert/strict');
const originalFetch=global.fetch,originalEnv={...process.env};
process.env.WAYFORPAY_SECRET_KEY='test_secret_key';process.env.WAYFORPAY_MERCHANT_ACCOUNT='test_merchant';process.env.PRICE_BASE='15';process.env.PRICE_PRO='25';process.env.PRICE_UPGRADE='10';process.env.PRODUCT_CURRENCY='USD';
const handler=require('./wayforpay-create.js');
function res(){return{code:0,body:null,headers:{},status(n){this.code=n;return this;},json(b){this.body=b;return this;},setHeader(k,v){this.headers[k]=v;}};}
async function run(over={}){const r=res();await handler({method:'POST',body:{email:' Buyer@Example.Test ',phone:'+380931234567',plan:'base',...over}},r);return r;}
function setLedger(mode){process.env.ACADEMY_LEDGER_MODE=mode;process.env.ACADEMY_LEDGER_URL='https://academy.example/api/payments';process.env.ACADEMY_LEDGER_SECRET='z'.repeat(40);delete process.env.ACADEMY_LEDGER_VERCEL_BYPASS;}

test('off mode makes no Academy request',async()=>{setLedger('off');let calls=0;global.fetch=async()=>{calls++;throw Error('should not fetch');};const r=await run();assert.equal(r.code,200);assert.equal(calls,0);});
test('shadow bridge failure preserves checkout',async()=>{setLedger('shadow');global.fetch=async()=>({ok:false,status:503,json:async()=>({error:'down'})});const r=await run();assert.equal(r.code,200);assert.match(r.body.orderReference,/^tv-base-/);});
test('required bridge failure blocks checkout payload',async()=>{setLedger('required');global.fetch=async()=>({ok:false,status:503,json:async()=>({error:'down'})});const r=await run();assert.equal(r.code,503);assert.equal(r.body.error,'academy_ledger_unavailable');});
test('required registration uses server-validated identity and catalog price',async()=>{setLedger('required');let sent;global.fetch=async(url,opts)=>{sent={url,opts,body:JSON.parse(opts.body)};return{ok:true,status:200,json:async()=>({ok:true})};};const r=await run({plan:'pro',price:0.01});assert.equal(r.code,200);assert.equal(sent.body.email,'buyer@example.test');assert.equal(sent.body.productId,'mini-pro');assert.equal(sent.body.amountMinor,2500);assert.equal(sent.body.currency,'USD');assert.equal(Object.hasOwn(sent.body,'price'),false);assert.match(sent.url,/action=register-order/);});
test('bridge forwards optional Vercel protection bypass only as a server header',async()=>{setLedger('required');const bypass='b'.repeat(40);process.env.ACADEMY_LEDGER_VERCEL_BYPASS=bypass;let sent;global.fetch=async(url,opts)=>{sent={url,opts,body:JSON.parse(opts.body)};return{ok:true,status:200,json:async()=>({ok:true})};};const r=await run();assert.equal(r.code,200);assert.equal(sent.opts.headers['x-vercel-protection-bypass'],bypass);assert.equal(JSON.stringify(sent.body).includes(bypass),false);assert.equal(sent.url.includes(bypass),false);});
after(()=>{global.fetch=originalFetch;for(const k of Object.keys(process.env))if(!(k in originalEnv))delete process.env[k];Object.assign(process.env,originalEnv);});
